version: '3'
services:
  mysql:
    build: ./mysql
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=passw0rd
      - TZ=Japan
    ports:
      - "3306:3306"
